import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/app/providers"
import Header from '@/components/header'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pat's Discussion App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body 
      className={inter.className}
      cz-shortcut-listen="true"
      >
        <div className="container mx-auto px-3 mas-w-6xl">

        
       
          <Providers>
             <Header/>
            {children}
            </Providers>
          </div>
        </body>
    </html>
  );
}
